#!/bin/sh

export XDG_CONFIG_DIRS="$HOME/.config/vistathemeplasma:/etc/xdg:$XDG_CONFIG_DIRS"
export PLASMA_DEFAULT_SHELL=io.gitgud.catpswin56.desktop

DBUS_WORKAROUND_EXEC="/usr/lib/plasma-dbus-run-session-if-needed"

if [ ! -f ${DBUS_WORKAROUND_EXEC} ]; then
    echo "DBus workaround not found, trying another common path."
	DBUS_WORKAROUND_EXEC="/usr/libexec/plasma-dbus-run-session-if-needed"
fi

$DBUS_WORKAROUND_EXEC /usr/bin/startplasma-wayland
