// PlymouthVista
// nativeglyphs.sp
// Defines glyphs for the native mode font
global.NativeGlyphImg = [];

fun InitNativeGlyphs() {
	global.NativeGlyphWidth = 8 * ScaleFactorX;
	global.NativeGlyphHeight = 14 * ScaleFactorY;
	
	global.NativeGlyphsMap = Image("glyphs.png");
	ScaledMapWidth = NativeGlyphsMap.GetWidth() * ScaleFactorX;
	ScaledMapHeight = NativeGlyphsMap.GetHeight() * ScaleFactorY;
	NativeGlyphsMap = NativeGlyphsMap.Scale(ScaledMapWidth, ScaledMapHeight);
	
	NativeGlyphImg[" "] = NativeGlyphsMap.Crop(0 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["!"] = NativeGlyphsMap.Crop(1 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["\""] = NativeGlyphsMap.Crop(2 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["#"] = NativeGlyphsMap.Crop(3 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["$"] = NativeGlyphsMap.Crop(4 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["%"] = NativeGlyphsMap.Crop(5 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["&"] = NativeGlyphsMap.Crop(6 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["'"] = NativeGlyphsMap.Crop(7 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["("] = NativeGlyphsMap.Crop(8 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[")"] = NativeGlyphsMap.Crop(9 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["*"] = NativeGlyphsMap.Crop(10 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["+"] = NativeGlyphsMap.Crop(11 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[","] = NativeGlyphsMap.Crop(12 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["-"] = NativeGlyphsMap.Crop(13 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["."] = NativeGlyphsMap.Crop(14 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["/"] = NativeGlyphsMap.Crop(15 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["0"] = NativeGlyphsMap.Crop(16 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["1"] = NativeGlyphsMap.Crop(17 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["2"] = NativeGlyphsMap.Crop(18 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["3"] = NativeGlyphsMap.Crop(19 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["4"] = NativeGlyphsMap.Crop(20 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["5"] = NativeGlyphsMap.Crop(21 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["6"] = NativeGlyphsMap.Crop(22 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["7"] = NativeGlyphsMap.Crop(23 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["8"] = NativeGlyphsMap.Crop(24 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["9"] = NativeGlyphsMap.Crop(25 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[":"] = NativeGlyphsMap.Crop(26 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[";"] = NativeGlyphsMap.Crop(27 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["<"] = NativeGlyphsMap.Crop(28 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["="] = NativeGlyphsMap.Crop(29 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[">"] = NativeGlyphsMap.Crop(30 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["?"] = NativeGlyphsMap.Crop(31 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["@"] = NativeGlyphsMap.Crop(32 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["A"] = NativeGlyphsMap.Crop(33 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["B"] = NativeGlyphsMap.Crop(34 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["C"] = NativeGlyphsMap.Crop(35 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["D"] = NativeGlyphsMap.Crop(36 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["E"] = NativeGlyphsMap.Crop(37 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["F"] = NativeGlyphsMap.Crop(38 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["G"] = NativeGlyphsMap.Crop(39 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["H"] = NativeGlyphsMap.Crop(40 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["I"] = NativeGlyphsMap.Crop(41 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["J"] = NativeGlyphsMap.Crop(42 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["K"] = NativeGlyphsMap.Crop(43 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["L"] = NativeGlyphsMap.Crop(44 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["M"] = NativeGlyphsMap.Crop(45 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["N"] = NativeGlyphsMap.Crop(46 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["O"] = NativeGlyphsMap.Crop(47 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["P"] = NativeGlyphsMap.Crop(48 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Q"] = NativeGlyphsMap.Crop(49 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["R"] = NativeGlyphsMap.Crop(50 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["S"] = NativeGlyphsMap.Crop(51 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["T"] = NativeGlyphsMap.Crop(52 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["U"] = NativeGlyphsMap.Crop(53 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["V"] = NativeGlyphsMap.Crop(54 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["W"] = NativeGlyphsMap.Crop(55 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["X"] = NativeGlyphsMap.Crop(56 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Y"] = NativeGlyphsMap.Crop(57 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Z"] = NativeGlyphsMap.Crop(58 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["["] = NativeGlyphsMap.Crop(59 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["\\"] = NativeGlyphsMap.Crop(60 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["]"] = NativeGlyphsMap.Crop(61 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["^"] = NativeGlyphsMap.Crop(62 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["_"] = NativeGlyphsMap.Crop(63 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["`"] = NativeGlyphsMap.Crop(64 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["a"] = NativeGlyphsMap.Crop(65 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["b"] = NativeGlyphsMap.Crop(66 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["c"] = NativeGlyphsMap.Crop(67 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["d"] = NativeGlyphsMap.Crop(68 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["e"] = NativeGlyphsMap.Crop(69 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["f"] = NativeGlyphsMap.Crop(70 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["g"] = NativeGlyphsMap.Crop(71 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["h"] = NativeGlyphsMap.Crop(72 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["i"] = NativeGlyphsMap.Crop(73 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["j"] = NativeGlyphsMap.Crop(74 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["k"] = NativeGlyphsMap.Crop(75 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["l"] = NativeGlyphsMap.Crop(76 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["m"] = NativeGlyphsMap.Crop(77 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["n"] = NativeGlyphsMap.Crop(78 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["o"] = NativeGlyphsMap.Crop(79 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["p"] = NativeGlyphsMap.Crop(80 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["q"] = NativeGlyphsMap.Crop(81 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["r"] = NativeGlyphsMap.Crop(82 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["s"] = NativeGlyphsMap.Crop(83 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["t"] = NativeGlyphsMap.Crop(84 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["u"] = NativeGlyphsMap.Crop(85 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["v"] = NativeGlyphsMap.Crop(86 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["w"] = NativeGlyphsMap.Crop(87 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["x"] = NativeGlyphsMap.Crop(88 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["y"] = NativeGlyphsMap.Crop(89 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["z"] = NativeGlyphsMap.Crop(90 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["{"] = NativeGlyphsMap.Crop(91 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["|"] = NativeGlyphsMap.Crop(92 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["}"] = NativeGlyphsMap.Crop(93 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["~"] = NativeGlyphsMap.Crop(94 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¡"] = NativeGlyphsMap.Crop(95 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¢"] = NativeGlyphsMap.Crop(96 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["£"] = NativeGlyphsMap.Crop(97 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¤"] = NativeGlyphsMap.Crop(98 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¥"] = NativeGlyphsMap.Crop(99 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¦"] = NativeGlyphsMap.Crop(100 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["§"] = NativeGlyphsMap.Crop(101 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¨"] = NativeGlyphsMap.Crop(102 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["©"] = NativeGlyphsMap.Crop(103 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ª"] = NativeGlyphsMap.Crop(104 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["«"] = NativeGlyphsMap.Crop(105 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¬"] = NativeGlyphsMap.Crop(106 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["®"] = NativeGlyphsMap.Crop(107 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¯"] = NativeGlyphsMap.Crop(108 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["°"] = NativeGlyphsMap.Crop(109 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["±"] = NativeGlyphsMap.Crop(110 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["²"] = NativeGlyphsMap.Crop(111 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["³"] = NativeGlyphsMap.Crop(112 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["´"] = NativeGlyphsMap.Crop(113 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["µ"] = NativeGlyphsMap.Crop(114 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¶"] = NativeGlyphsMap.Crop(115 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["·"] = NativeGlyphsMap.Crop(116 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¸"] = NativeGlyphsMap.Crop(117 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¹"] = NativeGlyphsMap.Crop(118 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["º"] = NativeGlyphsMap.Crop(119 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["»"] = NativeGlyphsMap.Crop(120 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¼"] = NativeGlyphsMap.Crop(121 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["½"] = NativeGlyphsMap.Crop(122 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¾"] = NativeGlyphsMap.Crop(123 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["¿"] = NativeGlyphsMap.Crop(124 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["À"] = NativeGlyphsMap.Crop(125 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Á"] = NativeGlyphsMap.Crop(126 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Â"] = NativeGlyphsMap.Crop(127 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ã"] = NativeGlyphsMap.Crop(128 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ä"] = NativeGlyphsMap.Crop(129 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Å"] = NativeGlyphsMap.Crop(130 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Æ"] = NativeGlyphsMap.Crop(131 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ç"] = NativeGlyphsMap.Crop(132 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["È"] = NativeGlyphsMap.Crop(133 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["É"] = NativeGlyphsMap.Crop(134 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ê"] = NativeGlyphsMap.Crop(135 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ë"] = NativeGlyphsMap.Crop(136 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ì"] = NativeGlyphsMap.Crop(137 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Í"] = NativeGlyphsMap.Crop(138 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Î"] = NativeGlyphsMap.Crop(139 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ï"] = NativeGlyphsMap.Crop(140 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ð"] = NativeGlyphsMap.Crop(141 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ñ"] = NativeGlyphsMap.Crop(142 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ò"] = NativeGlyphsMap.Crop(143 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ó"] = NativeGlyphsMap.Crop(144 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ô"] = NativeGlyphsMap.Crop(145 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Õ"] = NativeGlyphsMap.Crop(146 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ö"] = NativeGlyphsMap.Crop(147 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["×"] = NativeGlyphsMap.Crop(148 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ø"] = NativeGlyphsMap.Crop(149 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ù"] = NativeGlyphsMap.Crop(150 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ú"] = NativeGlyphsMap.Crop(151 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Û"] = NativeGlyphsMap.Crop(152 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ü"] = NativeGlyphsMap.Crop(153 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ý"] = NativeGlyphsMap.Crop(154 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Þ"] = NativeGlyphsMap.Crop(155 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ß"] = NativeGlyphsMap.Crop(156 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["à"] = NativeGlyphsMap.Crop(157 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["á"] = NativeGlyphsMap.Crop(158 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["â"] = NativeGlyphsMap.Crop(159 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ã"] = NativeGlyphsMap.Crop(160 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ä"] = NativeGlyphsMap.Crop(161 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["å"] = NativeGlyphsMap.Crop(162 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["æ"] = NativeGlyphsMap.Crop(163 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ç"] = NativeGlyphsMap.Crop(164 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["è"] = NativeGlyphsMap.Crop(165 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["é"] = NativeGlyphsMap.Crop(166 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ê"] = NativeGlyphsMap.Crop(167 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ë"] = NativeGlyphsMap.Crop(168 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ì"] = NativeGlyphsMap.Crop(169 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["í"] = NativeGlyphsMap.Crop(170 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["î"] = NativeGlyphsMap.Crop(171 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ï"] = NativeGlyphsMap.Crop(172 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ð"] = NativeGlyphsMap.Crop(173 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ñ"] = NativeGlyphsMap.Crop(174 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ò"] = NativeGlyphsMap.Crop(175 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ó"] = NativeGlyphsMap.Crop(176 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ô"] = NativeGlyphsMap.Crop(177 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["õ"] = NativeGlyphsMap.Crop(178 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ö"] = NativeGlyphsMap.Crop(179 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["÷"] = NativeGlyphsMap.Crop(180 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ø"] = NativeGlyphsMap.Crop(181 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ù"] = NativeGlyphsMap.Crop(182 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ú"] = NativeGlyphsMap.Crop(183 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["û"] = NativeGlyphsMap.Crop(184 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ü"] = NativeGlyphsMap.Crop(185 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ý"] = NativeGlyphsMap.Crop(186 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["þ"] = NativeGlyphsMap.Crop(187 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ÿ"] = NativeGlyphsMap.Crop(188 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ā"] = NativeGlyphsMap.Crop(189 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ā"] = NativeGlyphsMap.Crop(190 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ă"] = NativeGlyphsMap.Crop(191 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ă"] = NativeGlyphsMap.Crop(192 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ą"] = NativeGlyphsMap.Crop(193 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ą"] = NativeGlyphsMap.Crop(194 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ć"] = NativeGlyphsMap.Crop(195 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ć"] = NativeGlyphsMap.Crop(196 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĉ"] = NativeGlyphsMap.Crop(197 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĉ"] = NativeGlyphsMap.Crop(198 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ċ"] = NativeGlyphsMap.Crop(199 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ċ"] = NativeGlyphsMap.Crop(200 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Č"] = NativeGlyphsMap.Crop(201 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["č"] = NativeGlyphsMap.Crop(202 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ď"] = NativeGlyphsMap.Crop(203 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ď"] = NativeGlyphsMap.Crop(204 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Đ"] = NativeGlyphsMap.Crop(205 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["đ"] = NativeGlyphsMap.Crop(206 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ē"] = NativeGlyphsMap.Crop(207 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ē"] = NativeGlyphsMap.Crop(208 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĕ"] = NativeGlyphsMap.Crop(209 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĕ"] = NativeGlyphsMap.Crop(210 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ė"] = NativeGlyphsMap.Crop(211 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ė"] = NativeGlyphsMap.Crop(212 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ę"] = NativeGlyphsMap.Crop(213 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ę"] = NativeGlyphsMap.Crop(214 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ě"] = NativeGlyphsMap.Crop(215 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ě"] = NativeGlyphsMap.Crop(216 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĝ"] = NativeGlyphsMap.Crop(217 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĝ"] = NativeGlyphsMap.Crop(218 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ğ"] = NativeGlyphsMap.Crop(219 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ğ"] = NativeGlyphsMap.Crop(220 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ġ"] = NativeGlyphsMap.Crop(221 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ġ"] = NativeGlyphsMap.Crop(222 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ģ"] = NativeGlyphsMap.Crop(223 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ģ"] = NativeGlyphsMap.Crop(224 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĥ"] = NativeGlyphsMap.Crop(225 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĥ"] = NativeGlyphsMap.Crop(226 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ħ"] = NativeGlyphsMap.Crop(227 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ħ"] = NativeGlyphsMap.Crop(228 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĩ"] = NativeGlyphsMap.Crop(229 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĩ"] = NativeGlyphsMap.Crop(230 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ī"] = NativeGlyphsMap.Crop(231 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ī"] = NativeGlyphsMap.Crop(232 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĭ"] = NativeGlyphsMap.Crop(233 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĭ"] = NativeGlyphsMap.Crop(234 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Į"] = NativeGlyphsMap.Crop(235 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["į"] = NativeGlyphsMap.Crop(236 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["İ"] = NativeGlyphsMap.Crop(237 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ı"] = NativeGlyphsMap.Crop(238 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĳ"] = NativeGlyphsMap.Crop(239 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĳ"] = NativeGlyphsMap.Crop(240 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĵ"] = NativeGlyphsMap.Crop(241 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĵ"] = NativeGlyphsMap.Crop(242 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ķ"] = NativeGlyphsMap.Crop(243 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ķ"] = NativeGlyphsMap.Crop(244 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĸ"] = NativeGlyphsMap.Crop(245 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ĺ"] = NativeGlyphsMap.Crop(246 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ĺ"] = NativeGlyphsMap.Crop(247 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ļ"] = NativeGlyphsMap.Crop(248 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ļ"] = NativeGlyphsMap.Crop(249 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ľ"] = NativeGlyphsMap.Crop(250 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ľ"] = NativeGlyphsMap.Crop(251 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŀ"] = NativeGlyphsMap.Crop(252 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŀ"] = NativeGlyphsMap.Crop(253 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ł"] = NativeGlyphsMap.Crop(254 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ł"] = NativeGlyphsMap.Crop(255 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ń"] = NativeGlyphsMap.Crop(256 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ń"] = NativeGlyphsMap.Crop(257 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ņ"] = NativeGlyphsMap.Crop(258 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ņ"] = NativeGlyphsMap.Crop(259 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ň"] = NativeGlyphsMap.Crop(260 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ň"] = NativeGlyphsMap.Crop(261 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŉ"] = NativeGlyphsMap.Crop(262 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŋ"] = NativeGlyphsMap.Crop(263 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŋ"] = NativeGlyphsMap.Crop(264 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ō"] = NativeGlyphsMap.Crop(265 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ō"] = NativeGlyphsMap.Crop(266 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŏ"] = NativeGlyphsMap.Crop(267 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŏ"] = NativeGlyphsMap.Crop(268 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ő"] = NativeGlyphsMap.Crop(269 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ő"] = NativeGlyphsMap.Crop(270 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Œ"] = NativeGlyphsMap.Crop(271 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["œ"] = NativeGlyphsMap.Crop(272 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŕ"] = NativeGlyphsMap.Crop(273 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŕ"] = NativeGlyphsMap.Crop(274 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŗ"] = NativeGlyphsMap.Crop(275 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŗ"] = NativeGlyphsMap.Crop(276 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ř"] = NativeGlyphsMap.Crop(277 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ř"] = NativeGlyphsMap.Crop(278 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ś"] = NativeGlyphsMap.Crop(279 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ś"] = NativeGlyphsMap.Crop(280 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŝ"] = NativeGlyphsMap.Crop(281 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŝ"] = NativeGlyphsMap.Crop(282 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ş"] = NativeGlyphsMap.Crop(283 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ş"] = NativeGlyphsMap.Crop(284 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Š"] = NativeGlyphsMap.Crop(285 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["š"] = NativeGlyphsMap.Crop(286 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ţ"] = NativeGlyphsMap.Crop(287 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ţ"] = NativeGlyphsMap.Crop(288 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ť"] = NativeGlyphsMap.Crop(289 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ť"] = NativeGlyphsMap.Crop(290 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŧ"] = NativeGlyphsMap.Crop(291 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŧ"] = NativeGlyphsMap.Crop(292 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ũ"] = NativeGlyphsMap.Crop(293 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ũ"] = NativeGlyphsMap.Crop(294 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ū"] = NativeGlyphsMap.Crop(295 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ū"] = NativeGlyphsMap.Crop(296 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŭ"] = NativeGlyphsMap.Crop(297 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŭ"] = NativeGlyphsMap.Crop(298 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ů"] = NativeGlyphsMap.Crop(299 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ů"] = NativeGlyphsMap.Crop(300 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ű"] = NativeGlyphsMap.Crop(301 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ű"] = NativeGlyphsMap.Crop(302 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ų"] = NativeGlyphsMap.Crop(303 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ų"] = NativeGlyphsMap.Crop(304 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŵ"] = NativeGlyphsMap.Crop(305 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŵ"] = NativeGlyphsMap.Crop(306 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ŷ"] = NativeGlyphsMap.Crop(307 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ŷ"] = NativeGlyphsMap.Crop(308 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ÿ"] = NativeGlyphsMap.Crop(309 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ź"] = NativeGlyphsMap.Crop(310 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ź"] = NativeGlyphsMap.Crop(311 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ż"] = NativeGlyphsMap.Crop(312 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ż"] = NativeGlyphsMap.Crop(313 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ž"] = NativeGlyphsMap.Crop(314 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ž"] = NativeGlyphsMap.Crop(315 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ſ"] = NativeGlyphsMap.Crop(316 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ƒ"] = NativeGlyphsMap.Crop(317 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ǻ"] = NativeGlyphsMap.Crop(318 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ǻ"] = NativeGlyphsMap.Crop(319 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ǽ"] = NativeGlyphsMap.Crop(320 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ǽ"] = NativeGlyphsMap.Crop(321 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ǿ"] = NativeGlyphsMap.Crop(322 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ǿ"] = NativeGlyphsMap.Crop(323 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ˆ"] = NativeGlyphsMap.Crop(324 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ˇ"] = NativeGlyphsMap.Crop(325 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ˉ"] = NativeGlyphsMap.Crop(326 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˘"] = NativeGlyphsMap.Crop(327 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˙"] = NativeGlyphsMap.Crop(328 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˚"] = NativeGlyphsMap.Crop(329 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˛"] = NativeGlyphsMap.Crop(330 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˜"] = NativeGlyphsMap.Crop(331 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["˝"] = NativeGlyphsMap.Crop(332 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg[";"] = NativeGlyphsMap.Crop(333 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["΄"] = NativeGlyphsMap.Crop(334 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["΅"] = NativeGlyphsMap.Crop(335 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ά"] = NativeGlyphsMap.Crop(336 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["·"] = NativeGlyphsMap.Crop(337 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Έ"] = NativeGlyphsMap.Crop(338 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ή"] = NativeGlyphsMap.Crop(339 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ί"] = NativeGlyphsMap.Crop(340 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ό"] = NativeGlyphsMap.Crop(341 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ύ"] = NativeGlyphsMap.Crop(342 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ώ"] = NativeGlyphsMap.Crop(343 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ΐ"] = NativeGlyphsMap.Crop(344 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Α"] = NativeGlyphsMap.Crop(345 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Β"] = NativeGlyphsMap.Crop(346 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Γ"] = NativeGlyphsMap.Crop(347 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Δ"] = NativeGlyphsMap.Crop(348 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ε"] = NativeGlyphsMap.Crop(349 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ζ"] = NativeGlyphsMap.Crop(350 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Η"] = NativeGlyphsMap.Crop(351 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Θ"] = NativeGlyphsMap.Crop(352 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ι"] = NativeGlyphsMap.Crop(353 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Κ"] = NativeGlyphsMap.Crop(354 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Λ"] = NativeGlyphsMap.Crop(355 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Μ"] = NativeGlyphsMap.Crop(356 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ν"] = NativeGlyphsMap.Crop(357 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ξ"] = NativeGlyphsMap.Crop(358 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ο"] = NativeGlyphsMap.Crop(359 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Π"] = NativeGlyphsMap.Crop(360 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ρ"] = NativeGlyphsMap.Crop(361 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Σ"] = NativeGlyphsMap.Crop(362 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Τ"] = NativeGlyphsMap.Crop(363 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Υ"] = NativeGlyphsMap.Crop(364 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Φ"] = NativeGlyphsMap.Crop(365 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Χ"] = NativeGlyphsMap.Crop(366 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ψ"] = NativeGlyphsMap.Crop(367 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ω"] = NativeGlyphsMap.Crop(368 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ϊ"] = NativeGlyphsMap.Crop(369 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ϋ"] = NativeGlyphsMap.Crop(370 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ά"] = NativeGlyphsMap.Crop(371 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["έ"] = NativeGlyphsMap.Crop(372 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ή"] = NativeGlyphsMap.Crop(373 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ί"] = NativeGlyphsMap.Crop(374 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ΰ"] = NativeGlyphsMap.Crop(375 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["α"] = NativeGlyphsMap.Crop(376 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["β"] = NativeGlyphsMap.Crop(377 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["γ"] = NativeGlyphsMap.Crop(378 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["δ"] = NativeGlyphsMap.Crop(379 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ε"] = NativeGlyphsMap.Crop(380 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ζ"] = NativeGlyphsMap.Crop(381 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["η"] = NativeGlyphsMap.Crop(382 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["θ"] = NativeGlyphsMap.Crop(383 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ι"] = NativeGlyphsMap.Crop(384 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["κ"] = NativeGlyphsMap.Crop(385 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["λ"] = NativeGlyphsMap.Crop(386 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["μ"] = NativeGlyphsMap.Crop(387 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ν"] = NativeGlyphsMap.Crop(388 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ξ"] = NativeGlyphsMap.Crop(389 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ο"] = NativeGlyphsMap.Crop(390 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["π"] = NativeGlyphsMap.Crop(391 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ρ"] = NativeGlyphsMap.Crop(392 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ς"] = NativeGlyphsMap.Crop(393 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["σ"] = NativeGlyphsMap.Crop(394 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["τ"] = NativeGlyphsMap.Crop(395 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["υ"] = NativeGlyphsMap.Crop(396 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["φ"] = NativeGlyphsMap.Crop(397 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["χ"] = NativeGlyphsMap.Crop(398 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ψ"] = NativeGlyphsMap.Crop(399 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ω"] = NativeGlyphsMap.Crop(400 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ϊ"] = NativeGlyphsMap.Crop(401 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ϋ"] = NativeGlyphsMap.Crop(402 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ό"] = NativeGlyphsMap.Crop(403 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ύ"] = NativeGlyphsMap.Crop(404 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ώ"] = NativeGlyphsMap.Crop(405 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ё"] = NativeGlyphsMap.Crop(406 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ђ"] = NativeGlyphsMap.Crop(407 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ѓ"] = NativeGlyphsMap.Crop(408 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Є"] = NativeGlyphsMap.Crop(409 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ѕ"] = NativeGlyphsMap.Crop(410 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["І"] = NativeGlyphsMap.Crop(411 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ї"] = NativeGlyphsMap.Crop(412 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ј"] = NativeGlyphsMap.Crop(413 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Љ"] = NativeGlyphsMap.Crop(414 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Њ"] = NativeGlyphsMap.Crop(415 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ћ"] = NativeGlyphsMap.Crop(416 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ќ"] = NativeGlyphsMap.Crop(417 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ў"] = NativeGlyphsMap.Crop(418 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Џ"] = NativeGlyphsMap.Crop(419 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["А"] = NativeGlyphsMap.Crop(420 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Б"] = NativeGlyphsMap.Crop(421 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["В"] = NativeGlyphsMap.Crop(422 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Г"] = NativeGlyphsMap.Crop(423 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Д"] = NativeGlyphsMap.Crop(424 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Е"] = NativeGlyphsMap.Crop(425 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ж"] = NativeGlyphsMap.Crop(426 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["З"] = NativeGlyphsMap.Crop(427 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["И"] = NativeGlyphsMap.Crop(428 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Й"] = NativeGlyphsMap.Crop(429 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["К"] = NativeGlyphsMap.Crop(430 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Л"] = NativeGlyphsMap.Crop(431 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["М"] = NativeGlyphsMap.Crop(432 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Н"] = NativeGlyphsMap.Crop(433 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["О"] = NativeGlyphsMap.Crop(434 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["П"] = NativeGlyphsMap.Crop(435 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Р"] = NativeGlyphsMap.Crop(436 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["С"] = NativeGlyphsMap.Crop(437 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Т"] = NativeGlyphsMap.Crop(438 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["У"] = NativeGlyphsMap.Crop(439 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ф"] = NativeGlyphsMap.Crop(440 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Х"] = NativeGlyphsMap.Crop(441 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ц"] = NativeGlyphsMap.Crop(442 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ч"] = NativeGlyphsMap.Crop(443 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ш"] = NativeGlyphsMap.Crop(444 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Щ"] = NativeGlyphsMap.Crop(445 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ъ"] = NativeGlyphsMap.Crop(446 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ы"] = NativeGlyphsMap.Crop(447 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ь"] = NativeGlyphsMap.Crop(448 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Э"] = NativeGlyphsMap.Crop(449 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ю"] = NativeGlyphsMap.Crop(450 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Я"] = NativeGlyphsMap.Crop(451 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["а"] = NativeGlyphsMap.Crop(452 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["б"] = NativeGlyphsMap.Crop(453 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["в"] = NativeGlyphsMap.Crop(454 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["г"] = NativeGlyphsMap.Crop(455 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["д"] = NativeGlyphsMap.Crop(456 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["е"] = NativeGlyphsMap.Crop(457 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ж"] = NativeGlyphsMap.Crop(458 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["з"] = NativeGlyphsMap.Crop(459 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["и"] = NativeGlyphsMap.Crop(460 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["й"] = NativeGlyphsMap.Crop(461 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["к"] = NativeGlyphsMap.Crop(462 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["л"] = NativeGlyphsMap.Crop(463 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["м"] = NativeGlyphsMap.Crop(464 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["н"] = NativeGlyphsMap.Crop(465 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["о"] = NativeGlyphsMap.Crop(466 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["п"] = NativeGlyphsMap.Crop(467 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["р"] = NativeGlyphsMap.Crop(468 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["с"] = NativeGlyphsMap.Crop(469 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["т"] = NativeGlyphsMap.Crop(470 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["у"] = NativeGlyphsMap.Crop(471 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ф"] = NativeGlyphsMap.Crop(472 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["х"] = NativeGlyphsMap.Crop(473 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ц"] = NativeGlyphsMap.Crop(474 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ч"] = NativeGlyphsMap.Crop(475 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ш"] = NativeGlyphsMap.Crop(476 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["щ"] = NativeGlyphsMap.Crop(477 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ъ"] = NativeGlyphsMap.Crop(478 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ы"] = NativeGlyphsMap.Crop(479 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ь"] = NativeGlyphsMap.Crop(480 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["э"] = NativeGlyphsMap.Crop(481 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ю"] = NativeGlyphsMap.Crop(482 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["я"] = NativeGlyphsMap.Crop(483 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ё"] = NativeGlyphsMap.Crop(484 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ђ"] = NativeGlyphsMap.Crop(485 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ѓ"] = NativeGlyphsMap.Crop(486 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["є"] = NativeGlyphsMap.Crop(487 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ѕ"] = NativeGlyphsMap.Crop(488 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["і"] = NativeGlyphsMap.Crop(489 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ї"] = NativeGlyphsMap.Crop(490 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ј"] = NativeGlyphsMap.Crop(491 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["љ"] = NativeGlyphsMap.Crop(492 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["њ"] = NativeGlyphsMap.Crop(493 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ћ"] = NativeGlyphsMap.Crop(494 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ќ"] = NativeGlyphsMap.Crop(495 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ў"] = NativeGlyphsMap.Crop(496 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["џ"] = NativeGlyphsMap.Crop(497 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ґ"] = NativeGlyphsMap.Crop(498 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ґ"] = NativeGlyphsMap.Crop(499 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ẁ"] = NativeGlyphsMap.Crop(500 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ẁ"] = NativeGlyphsMap.Crop(501 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ẃ"] = NativeGlyphsMap.Crop(502 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ẃ"] = NativeGlyphsMap.Crop(503 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ẅ"] = NativeGlyphsMap.Crop(504 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ẅ"] = NativeGlyphsMap.Crop(505 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ỳ"] = NativeGlyphsMap.Crop(506 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ỳ"] = NativeGlyphsMap.Crop(507 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["–"] = NativeGlyphsMap.Crop(508 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["—"] = NativeGlyphsMap.Crop(509 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["―"] = NativeGlyphsMap.Crop(510 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‗"] = NativeGlyphsMap.Crop(511 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‘"] = NativeGlyphsMap.Crop(512 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["’"] = NativeGlyphsMap.Crop(513 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‚"] = NativeGlyphsMap.Crop(514 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["“"] = NativeGlyphsMap.Crop(515 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["”"] = NativeGlyphsMap.Crop(516 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["„"] = NativeGlyphsMap.Crop(517 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["†"] = NativeGlyphsMap.Crop(518 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‡"] = NativeGlyphsMap.Crop(519 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["•"] = NativeGlyphsMap.Crop(520 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["…"] = NativeGlyphsMap.Crop(521 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‰"] = NativeGlyphsMap.Crop(522 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‹"] = NativeGlyphsMap.Crop(523 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["›"] = NativeGlyphsMap.Crop(524 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‼"] = NativeGlyphsMap.Crop(525 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["‾"] = NativeGlyphsMap.Crop(526 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⁄"] = NativeGlyphsMap.Crop(527 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ⁿ"] = NativeGlyphsMap.Crop(528 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["₣"] = NativeGlyphsMap.Crop(529 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["₤"] = NativeGlyphsMap.Crop(530 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["₧"] = NativeGlyphsMap.Crop(531 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["€"] = NativeGlyphsMap.Crop(532 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["№"] = NativeGlyphsMap.Crop(533 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["™"] = NativeGlyphsMap.Crop(534 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["Ω"] = NativeGlyphsMap.Crop(535 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⅛"] = NativeGlyphsMap.Crop(536 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⅜"] = NativeGlyphsMap.Crop(537 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⅝"] = NativeGlyphsMap.Crop(538 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⅞"] = NativeGlyphsMap.Crop(539 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["←"] = NativeGlyphsMap.Crop(540 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["↑"] = NativeGlyphsMap.Crop(541 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["→"] = NativeGlyphsMap.Crop(542 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["↓"] = NativeGlyphsMap.Crop(543 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["↔"] = NativeGlyphsMap.Crop(544 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["↕"] = NativeGlyphsMap.Crop(545 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["↨"] = NativeGlyphsMap.Crop(546 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∂"] = NativeGlyphsMap.Crop(547 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∆"] = NativeGlyphsMap.Crop(548 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∏"] = NativeGlyphsMap.Crop(549 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∑"] = NativeGlyphsMap.Crop(550 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["−"] = NativeGlyphsMap.Crop(551 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∙"] = NativeGlyphsMap.Crop(552 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["√"] = NativeGlyphsMap.Crop(553 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∞"] = NativeGlyphsMap.Crop(554 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∟"] = NativeGlyphsMap.Crop(555 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∩"] = NativeGlyphsMap.Crop(556 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["∫"] = NativeGlyphsMap.Crop(557 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["≈"] = NativeGlyphsMap.Crop(558 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["≠"] = NativeGlyphsMap.Crop(559 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["≡"] = NativeGlyphsMap.Crop(560 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["≤"] = NativeGlyphsMap.Crop(561 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["≥"] = NativeGlyphsMap.Crop(562 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⌂"] = NativeGlyphsMap.Crop(563 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⌐"] = NativeGlyphsMap.Crop(564 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⌠"] = NativeGlyphsMap.Crop(565 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["⌡"] = NativeGlyphsMap.Crop(566 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["─"] = NativeGlyphsMap.Crop(567 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["│"] = NativeGlyphsMap.Crop(568 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┌"] = NativeGlyphsMap.Crop(569 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┐"] = NativeGlyphsMap.Crop(570 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["└"] = NativeGlyphsMap.Crop(571 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┘"] = NativeGlyphsMap.Crop(572 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["├"] = NativeGlyphsMap.Crop(573 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┤"] = NativeGlyphsMap.Crop(574 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┬"] = NativeGlyphsMap.Crop(575 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┴"] = NativeGlyphsMap.Crop(576 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["┼"] = NativeGlyphsMap.Crop(577 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["═"] = NativeGlyphsMap.Crop(578 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["║"] = NativeGlyphsMap.Crop(579 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╒"] = NativeGlyphsMap.Crop(580 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╓"] = NativeGlyphsMap.Crop(581 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╔"] = NativeGlyphsMap.Crop(582 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╕"] = NativeGlyphsMap.Crop(583 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╖"] = NativeGlyphsMap.Crop(584 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╗"] = NativeGlyphsMap.Crop(585 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╘"] = NativeGlyphsMap.Crop(586 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╙"] = NativeGlyphsMap.Crop(587 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╚"] = NativeGlyphsMap.Crop(588 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╛"] = NativeGlyphsMap.Crop(589 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╜"] = NativeGlyphsMap.Crop(590 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╝"] = NativeGlyphsMap.Crop(591 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╞"] = NativeGlyphsMap.Crop(592 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╟"] = NativeGlyphsMap.Crop(593 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╠"] = NativeGlyphsMap.Crop(594 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╡"] = NativeGlyphsMap.Crop(595 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╢"] = NativeGlyphsMap.Crop(596 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╣"] = NativeGlyphsMap.Crop(597 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╤"] = NativeGlyphsMap.Crop(598 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╥"] = NativeGlyphsMap.Crop(599 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╦"] = NativeGlyphsMap.Crop(600 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╧"] = NativeGlyphsMap.Crop(601 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╨"] = NativeGlyphsMap.Crop(602 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╩"] = NativeGlyphsMap.Crop(603 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╪"] = NativeGlyphsMap.Crop(604 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╫"] = NativeGlyphsMap.Crop(605 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["╬"] = NativeGlyphsMap.Crop(606 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▀"] = NativeGlyphsMap.Crop(607 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▄"] = NativeGlyphsMap.Crop(608 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["█"] = NativeGlyphsMap.Crop(609 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▌"] = NativeGlyphsMap.Crop(610 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▐"] = NativeGlyphsMap.Crop(611 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["░"] = NativeGlyphsMap.Crop(612 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▒"] = NativeGlyphsMap.Crop(613 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▓"] = NativeGlyphsMap.Crop(614 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["■"] = NativeGlyphsMap.Crop(615 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▬"] = NativeGlyphsMap.Crop(616 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▲"] = NativeGlyphsMap.Crop(617 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["►"] = NativeGlyphsMap.Crop(618 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["▼"] = NativeGlyphsMap.Crop(619 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["◄"] = NativeGlyphsMap.Crop(620 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["◊"] = NativeGlyphsMap.Crop(621 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["○"] = NativeGlyphsMap.Crop(622 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["◘"] = NativeGlyphsMap.Crop(623 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["◙"] = NativeGlyphsMap.Crop(624 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["☺"] = NativeGlyphsMap.Crop(625 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["☻"] = NativeGlyphsMap.Crop(626 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["☼"] = NativeGlyphsMap.Crop(627 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♀"] = NativeGlyphsMap.Crop(628 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♂"] = NativeGlyphsMap.Crop(629 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♠"] = NativeGlyphsMap.Crop(630 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♣"] = NativeGlyphsMap.Crop(631 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♥"] = NativeGlyphsMap.Crop(632 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♦"] = NativeGlyphsMap.Crop(633 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♪"] = NativeGlyphsMap.Crop(634 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["♫"] = NativeGlyphsMap.Crop(635 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ﬁ"] = NativeGlyphsMap.Crop(636 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["ﬂ"] = NativeGlyphsMap.Crop(637 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
	NativeGlyphImg["unknown"] = NativeGlyphsMap.Crop(638 * NativeGlyphWidth, 0, NativeGlyphWidth, NativeGlyphHeight);
}

fun GetNativeGlyph(char) {
	glyph = NativeGlyphImg[char];
	if (!glyph) {
		return NativeGlyphImg["unknown"];
	} else {
		return glyph;
	}
}
// PlymouthVista
// boot.sp
// Defines the standard boot screen class

fun BootScreenNew() {
	local.self = [];
	
	self.BaseSprite = Sprite();
	self.ProgressSprite = Sprite();

	self.BaseImage = Image("base.png");
	self.ProgressImage = Image("progress.png");

	self.State = "fadein";
	self.Opacity = 0;
	self.FadeSteps = 15;

	// I could directly use the screen width & height here, but
	// I want to follow the pattern of using the scale factors.
	self.BaseScaledWidth = self.BaseImage.GetWidth() * ScaleFactorX;
	self.BaseScaledHeight = self.BaseImage.GetHeight() * ScaleFactorY;

	self.ProgressScaledWidth = self.ProgressImage.GetWidth() * ScaleFactorX;
	self.ProgressScaledHeight = self.ProgressImage.GetHeight() * ScaleFactorY;

	self.BaseImageScaled = self.BaseImage.Scale(self.BaseScaledWidth, self.BaseScaledHeight);
	self.ProgressImageScaled = self.ProgressImage.Scale(self.ProgressScaledWidth, self.ProgressScaledHeight);

	self.BaseSprite.SetImage(self.BaseImageScaled);
	self.BaseSprite.SetOpacity(0);
	self.BaseSprite.SetZ(1);

	// Progress co-ordinate stuff
	self.ProgressOriginX = 234 * ScaleFactorX;
	self.ProgressReturnX = (234 + (18 * 8)) * ScaleFactorX;
	self.ProgressCurrentX = self.ProgressOriginX;
	self.ProgressStepX = 8 * ScaleFactorX;
	self.ProgressY = 354 * ScaleFactorY;

	self.ProgressSprite.SetImage(self.ProgressImageScaled);
	self.ProgressSprite.SetOpacity(0);
	self.ProgressSprite.SetZ(0);
	self.ProgressSprite.SetX(self.ProgressCurrentX);
	self.ProgressSprite.SetY(self.ProgressY);
	
	fun Update(self) {
		// What state are we in?
		if (self.State == "fadein") {
			// Fade in, let's increment our opacity
			self.Opacity += (1 / self.FadeSteps);
			
			if (self.Opacity >= 1) {
				self.State = "progress";
				self.Opacity = 1;
			}
			
			self.BaseSprite.SetOpacity(self.Opacity);
		}
		if (self.State == "progress") {
			// Progress, let's increment the position of the progress dots
			self.ProgressSprite.SetOpacity(1);
			self.ProgressCurrentX += self.ProgressStepX;
			self.ProgressSprite.SetX(self.ProgressCurrentX);
			
			if (self.ProgressCurrentX > self.ProgressReturnX) {
				self.ProgressCurrentX = self.ProgressOriginX;
			}
		}
	}

	self.Update = Update;
	
	return self;
}
# native.sp
# TODO define "native mode" things here
# e.g encrypted volume password entry & boot message handling
// PlymouthVista
// nativetext.sp
// TODO define actual text region here with sprites (2d array? is it possible with plymouth?)
// also define convenience functions to print a line to our emulated "terminal" that calculates
// wrapping and line shuffling up etc automatically
// note to self: plymouth calls arrays "hashes" and they work more like lua tables than arrays
// also note to self: plymouth seems to provide no functions for string length..
// but String.CharAt returns empty when the end has been reached, so there's that.
// https://github.com/freedesktop/plymouth/blob/master/src/plugins/splash/script/script-lib-string.c#L54

fun NativeTextNew() {
	local.self = [];
	
	self.Rows = 22; // Verified with GIMP. Leaves 32px on the top & bottom of the screen, nice!
	self.Columns = 72; // Same as above, copypasted a bunch of glyph cells. 32px surrounds the text.
	
	self.X = 32 * ScaleFactorX;
	self.Y = 79 * ScaleFactorY;
	
	// Initialize characters
	self.Characters = [];
	for (y=0; y < self.Rows; y++) {
		for (x=0; x < self.Columns; x++) {
			self.Characters[y][x] = Sprite(GetNativeGlyph("NoGlyph"));
			self.Characters[y][x].SetX(self.X + (x * NativeGlyphWidth));
			self.Characters[y][x].SetY(self.Y + (y * NativeGlyphHeight));
			self.Characters[y][x].SetZ(1);
			self.Characters[y][x].SetOpacity(0);
		}
	}
	
	fun SetOpacity(self, opac) {
		for (y=0; y < self.Columns; y++) {
			for (x=0; x < self.Rows; x++) {
				self.Characters[x][y].SetOpacity(opac);
			}
		}
	}
	self.SetOpacity = SetOpacity;
	
	return self;
}
// PlymouthVista
// Plymouth theme to emulate the Windows Vista boot sequences.
// 
// No copyrighted assets are distributed with this project.
// You must prepare the required assets yourself.
// This project includes a Python script to automate this process for you.
// See prepare_assets/README for details.
// 
// "Windows Vista" is a registered trademark of Microsoft Corporation.
// The author(s) of this software are in no way affiliated with or endorsed by Microsoft Corporation,
// in any capacity. This project is a fan-made labor of love that sees NO PROFITS WHATSOEVER, donations or otherwise.

Window.SetBackgroundColor(0, 0, 0);

ScaleFactorX = Window.GetWidth() / 640;
ScaleFactorY = Window.GetHeight() / 480;

BootScreen = BootScreenNew();

fun RefreshCallback() {
	if (Plymouth.GetMode() == "boot" || Plymouth.GetMode() == "resume") {
		BootScreen.Update(BootScreen);
	}
}

Plymouth.SetRefreshRate(12);
Plymouth.SetRefreshFunction(RefreshCallback);
